### ISSUE TITLE
next cache configuration

### ISSUE THREAD

**Issue by e-papanicolas** [clearviction-devs/clearviction-wa#233]
In our github actions logs we are getting a message from next that no build cache is found, however we are setting up a cache, just not all the way.

**The logs:**
![image](https://github.com/clearviction-devs/clearviction-wa/assets/76261375/3c1c0e13-3a3a-4a8d-8e0a-5678da9b7f83)

**The file:**
<img width="1003" alt="Screenshot 2024-03-25 at 5 36 00 PM" src="https://github.com/clearviction-devs/clearviction-wa/assets/76261375/f004e5c1-6254-4111-a3bb-9c1d399aae08">

**From [next.js docs](https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions) about caching:**
![image](https://github.com/clearviction-devs/clearviction-wa/assets/76261375/a8fc6de0-8d6b-4b6e-8cb0-101822d942c3)

I think if we add restore keys this can be resolved.

**Comment by LeoFuna** [comment]
@e-papanicolas this warning is just to make sure that your are not building next more than 1 time.

In this workflow we just build next one time and then we use it, so we do not need to cache next.
What we are caching on `cache/v4` is not `next` but is just the environment that we created from job `install`.

If we try to cache next as doc says, we will receive an error because we dont have `next` previously builded.
